# Generated by Django 5.2.12 on 2026-03-08 02:03

from django.db import migrations


DEFAULT_PRIORITIES = [
    {"name": "Low", "slug": "low", "color": "#6B7280", "position": 0, "is_default": False},
    {"name": "Medium", "slug": "medium", "color": "#3B82F6", "position": 1, "is_default": True},
    {"name": "High", "slug": "high", "color": "#F97316", "position": 2, "is_default": False},
    {"name": "Urgent", "slug": "urgent", "color": "#EF4444", "position": 3, "is_default": False},
]


def seed_priorities(apps, schema_editor):
    """Create default priority levels for all existing organizations."""
    Organization = apps.get_model("organizations", "Organization")
    PriorityLevel = apps.get_model("tickets", "PriorityLevel")

    for org in Organization.objects.all():
        for p in DEFAULT_PRIORITIES:
            PriorityLevel.objects.get_or_create(
                organization=org,
                slug=p["slug"],
                defaults=p,
            )


def reverse_seed(apps, schema_editor):
    """Remove default priority levels."""
    PriorityLevel = apps.get_model("tickets", "PriorityLevel")
    PriorityLevel.objects.filter(slug__in=["low", "medium", "high", "urgent"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_priority_level_model'),
    ]

    operations = [
        migrations.RunPython(seed_priorities, reverse_seed),
    ]
