# Generated by Django 5.2.13 on 2026-04-24 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_showdesk_internal_org"),
        ("tickets", "0008_ticket_widget_last_read_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CannedResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "shortcut",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short slash command (e.g. 'merci') for quick filtering.",
                        max_length=50,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="If true, visible to all agents in the organization.",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_responses",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
                "unique_together": {("organization", "name")},
            },
        ),
    ]
