# Generated by Django 5.2.13 on 2026-05-01 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_organization_email_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("is_branding", models.BooleanField(default=False)),
                ("is_email_routing", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin_email", "Admin email"),
                            ("dns_txt", "DNS TXT"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True,
                        help_text="Random token the admin embeds in the DNS TXT record.",
                        max_length=64,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "status"],
                        name="organizatio_domain_ce2c24_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "domain"), name="unique_org_domain"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "verified")),
                        fields=("domain",),
                        name="unique_verified_domain_globally",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_branding", True),
                            ("is_email_routing", True),
                            _connector="OR",
                        ),
                        name="domain_has_at_least_one_purpose",
                    ),
                ],
            },
        ),
    ]
