# Generated by Django 5.2.13 on 2026-05-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_backfill_organization_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email_domain',
        ),
    ]
