# Generated by Django 5.2.13 on 2026-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0012_organization_email_from_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="feature_flag_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-org feature toggles, e.g. {'ai_categorization': true}. Each entry overrides the plan default for that flag.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Cloud Starter"),
                    ("business", "Cloud Business"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                help_text="Billing tier. Drives the default feature-flag set.",
                max_length=20,
            ),
        ),
    ]
